// <auto-generated>[WireMessage] 消息族线编码（spec-12 §10 E2——[Tag 1B][根字段声明序][子类字段声明序]；tag 判别/前缀/字段序/字节序全部生成物）</auto-generated>
#nullable enable
using System;   // 生成文件自足——不依赖消费方的 ImplicitUsings
using System.Buffers;
using System.Buffers.Binary;
using System.Diagnostics.CodeAnalysis;
namespace Golden.Fixtures;

/// <summary>FamilyMsg 消息族线编码——[WireMessage] 派生。</summary>
public static class FamilyMsgCodec
{
    /// <summary>Full 的 tag。</summary>
    public const byte TagFull = 0x01;

    /// <summary>Minimal 的 tag。</summary>
    public const byte TagMinimal = 0x02;


    /// <summary>编码（tag 判别 + 根前缀 + 子类字段）。返回新数组。</summary>
    public static byte[] Encode(FamilyMsg message)
    {
        var buffer = new byte[ComputeLength(message)];
        EncodeInto(buffer, message);
        return buffer;
    }


    /// <summary>编码到池化租借缓冲（零分配热路径——返回写入长度；缓冲由调用方
    /// <c>ArrayPool&lt;byte&gt;.Shared.Return(rented)</c> 归还。载荷经传输同步拷贝入帧后即可归还）。</summary>
    public static int EncodePooled(FamilyMsg message, out byte[] rented)
    {
        var len = ComputeLength(message);
        rented = ArrayPool<byte>.Shared.Rent(len);
        EncodeInto(rented.AsSpan(0, len), message);
        return len;
    }


    /// <summary>编码到 <see cref="System.Buffers.IBufferWriter{Byte}"/>（零拷贝汇——PipeWriter 直写形态）。</summary>
    public static void Encode(System.Buffers.IBufferWriter<byte> writer, FamilyMsg message)
    {
        var len = ComputeLength(message);
        var span = writer.GetSpan(len);
        EncodeInto(span, message);
        writer.Advance(len);
    }


    /// <summary>总长（单趟遍历——变长成员计数；池化/直写形态的长度预算口）。</summary>
    public static int ComputeLength(FamilyMsg message)
    {
        int cursor = 1;   // tag
        switch (message)
        {
            case Full m:
            {
                cursor += 8;
                cursor += 1;
                cursor += 4;
                cursor += Golden.Fixtures.ItemCodec.StructSize;
                cursor += 4 + m.Blob.Length;
                cursor += 4 + m.Memory.Length;
                cursor += 4;
                cursor += m.Flags.Length * 1;
                cursor += 4;
                cursor += m.Ids.Length * 4;
                cursor += 4;
                cursor += m.Items.Length * Golden.Fixtures.ItemCodec.StructSize;
                cursor += 4;
                foreach (var it in m.Chunks) cursor += 4 + it.Length;
                return cursor;
            }

            case Minimal m:
            {
                cursor += 8;
                return cursor;
            }

            default: throw new System.ArgumentException($"未知消息类型：{message.GetType().Name}。", nameof(message));
        }
    }


    /// <summary>写入调用方缓冲（零拷贝一等形态——长度须先经 ComputeLength）。</summary>
    public static void EncodeInto(Span<byte> dest, FamilyMsg message)
    {
        int cursor = 0;
        switch (message)
        {
            case Full m:
            {
                dest[cursor] = TagFull; cursor += 1;
                BinaryPrimitives.WriteInt64LittleEndian(dest[cursor..], m.Version); cursor += 8;
                dest[cursor] = m.Flag ? (byte)1 : (byte)0; cursor += 1;
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Count); cursor += 4;
                Golden.Fixtures.ItemCodec.Write(dest[cursor..], m.Origin); cursor += Golden.Fixtures.ItemCodec.StructSize;
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Blob.Length); cursor += 4;
                m.Blob.CopyTo(dest[cursor..]); cursor += m.Blob.Length;
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Memory.Length); cursor += 4;
                m.Memory.Span.CopyTo(dest[cursor..]); cursor += m.Memory.Length;
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Flags.Length); cursor += 4;
                foreach (var it in m.Flags)
                {
                    dest[cursor] = it ? (byte)1 : (byte)0; cursor += 1;
                }
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Ids.Length); cursor += 4;
                foreach (var it in m.Ids)
                {
                    BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], it); cursor += 4;
                }
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Items.Length); cursor += 4;
                foreach (var it in m.Items)
                {
                    Golden.Fixtures.ItemCodec.Write(dest[cursor..], it); cursor += Golden.Fixtures.ItemCodec.StructSize;
                }
                BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], m.Chunks.Count); cursor += 4;
                foreach (var it in m.Chunks)
                {
                    BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], it.Length); cursor += 4;
                    it.Span.CopyTo(dest[cursor..]); cursor += it.Length;
                }
                return;
            }

            case Minimal m:
            {
                dest[cursor] = TagMinimal; cursor += 1;
                BinaryPrimitives.WriteInt64LittleEndian(dest[cursor..], m.Version); cursor += 8;
                return;
            }

            default: throw new System.ArgumentException($"未知消息类型：{message.GetType().Name}。", nameof(message));
        }
    }


    /// <summary>解码（未知 tag/截断/Count 超上限 = false——畸形报文拦截；逐字段防御）。</summary>
    public static bool TryDecode(ReadOnlySpan<byte> source, [NotNullWhen(true)] out FamilyMsg? message)
    {
        message = null;
        int cursor = 0;
        if (source.Length < 1) return false;
        byte tag = source[0]; cursor += 1;
        switch (tag)
        {
            case TagFull:
            {
                if (source.Length < cursor + 8) return false;
                var version = BinaryPrimitives.ReadInt64LittleEndian(source[cursor..].Slice(0, 8)); cursor += 8;
                if (source.Length < cursor + 1) return false;
                var flag = source[cursor] != 0; cursor += 1;
                if (source.Length < cursor + 4) return false;
                var count = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..].Slice(0, 4)); cursor += 4;
                if (source.Length < cursor + Golden.Fixtures.ItemCodec.StructSize) return false;
                var origin = Golden.Fixtures.ItemCodec.Read(source.Slice(cursor, Golden.Fixtures.ItemCodec.StructSize)); cursor += Golden.Fixtures.ItemCodec.StructSize;
                if (source.Length < cursor + 4) return false;
                int blobLen = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]);
                if ((uint)blobLen > 64) return false;
                if (source.Length < cursor + 4 + blobLen) return false;
                var blob = source.Slice(cursor + 4, blobLen).ToArray(); cursor += 4 + blobLen;
                if (source.Length < cursor + 4) return false;
                int memoryLen = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]);
                if ((uint)memoryLen > 4) return false;
                if (source.Length < cursor + 4 + memoryLen) return false;
                var memory = source.Slice(cursor + 4, memoryLen).ToArray(); cursor += 4 + memoryLen;
                if (source.Length < cursor + 4) return false;
                int flagsCount = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]); cursor += 4;
                if ((uint)flagsCount > 4) return false;
                if (source.Length < cursor + flagsCount) return false;
                var flags = new bool[flagsCount];
                for (int i = 0; i < flagsCount; i++)
                {
                    if (source.Length < cursor + 1) return false;
                    flags[i] = source[cursor] != 0; cursor += 1;
                }
                if (source.Length < cursor + 4) return false;
                int idsCount = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]); cursor += 4;
                if ((uint)idsCount > 8) return false;
                if (source.Length < cursor + idsCount * 4) return false;
                var ids = new int[idsCount];
                for (int i = 0; i < idsCount; i++)
                {
                    if (source.Length < cursor + 4) return false;
                    ids[i] = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..].Slice(0, 4)); cursor += 4;
                }
                if (source.Length < cursor + 4) return false;
                int itemsCount = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]); cursor += 4;
                if ((uint)itemsCount > 8) return false;
                if (source.Length < cursor + itemsCount * Golden.Fixtures.ItemCodec.StructSize) return false;
                var items = new Golden.Fixtures.Item[itemsCount];
                for (int i = 0; i < itemsCount; i++)
                {
                    if (source.Length < cursor + Golden.Fixtures.ItemCodec.StructSize) return false;
                    items[i] = Golden.Fixtures.ItemCodec.Read(source.Slice(cursor, Golden.Fixtures.ItemCodec.StructSize)); cursor += Golden.Fixtures.ItemCodec.StructSize;
                }
                if (source.Length < cursor + 4) return false;
                int chunksCount = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]); cursor += 4;
                if ((uint)chunksCount > 4) return false;
                var chunks = new System.ReadOnlyMemory<byte>[chunksCount];
                for (int i = 0; i < chunksCount; i++)
                {
                    if (source.Length < cursor + 4) return false;
                    int len = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]);
                    if (len < 0 || source.Length < cursor + 4 + len) return false;
                    chunks[i] = source.Slice(cursor + 4, len).ToArray(); cursor += 4 + len;
                }
                message = new Full {
                    Version = version,
                    Flag = flag,
                    Count = count,
                    Origin = origin,
                    Blob = blob,
                    Memory = memory,
                    Flags = flags,
                    Ids = ids,
                    Items = items,
                    Chunks = chunks,
                };
                return true;
            }

            case TagMinimal:
            {
                if (source.Length < cursor + 8) return false;
                var version = BinaryPrimitives.ReadInt64LittleEndian(source[cursor..].Slice(0, 8)); cursor += 8;
                message = new Minimal {
                    Version = version,
                };
                return true;
            }

            default: return false;   // 未知 tag——向前兼容丢弃
        }
    }

}
