<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>12.0</LangVersion>
    <IsPackable>false</IsPackable>
    <NoWarn>CA1707,CA1716,CA1861,xUnit1000,xUnit1031,NU1507</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <!-- 契约平权基类复用（ObjectStoreContractTests public 跨工程继承） -->
    <ProjectReference Include="..\..\src\TC.Tier.Core.IO.S3\TC.Tier.Core.IO.S3.csproj" />
    <ProjectReference Include="..\TC.Tier.Core.Tests\TC.Tier.Core.Tests.csproj" />
  </ItemGroup>

</Project>
