// <auto-generated>[RingKey] 封闭薄类——比较族索引（BTree/SkipList）（ring-generic-key 设计稿 §2——一行 [RingKey] 声明产出全套封闭形态）</auto-generated>
#pragma warning disable 1591 // 生成封闭形态成员不进 API 文档
#nullable enable

namespace TC.Tier.Runtime.Structures.SortedIndex;

/// <summary><c>[RingKey(typeof(...))]</c> 比较族封闭薄类——keyResolver 可选（判等不需要，恢复重放需要）。</summary>
public sealed class BTreeOfTestKey : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<global::Golden.Fixtures.TestKey>
{
    public BTreeOfTestKey(global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.TestKey>? keyResolver = null,
        global::TC.Tier.Core.Primitives.IKeyComparer<global::Golden.Fixtures.TestKey>? keyComparer = null)
        : base(fs, settings, epoch, keyResolver, keyComparer)
    {
    }

    /// <summary>★ 工厂（异步）：构造 + Initialize(hints) + WaitForReadyAsync 一步到位——hints 注入恢复窗口（缺省空结构首开）；同步 WaitForReady 在异步上下文死锁，异步调用方禁用。</summary>
    public static async global::System.Threading.Tasks.Task<BTreeOfTestKey> CreateAsync(global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.TestKey>? keyResolver = null,
        global::TC.Tier.Core.Primitives.IKeyComparer<global::Golden.Fixtures.TestKey>? keyComparer = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        var index = new BTreeOfTestKey(fs, settings, epoch, keyResolver, keyComparer);
        index.Initialize(hints);
        await index.WaitForReadyAsync(ct);
        return index;
    }
}

/// <summary><c>[RingKey(typeof(...))]</c> 比较族封闭薄类——keyResolver 可选（判等不需要，恢复重放需要）。</summary>
public sealed class SkipListOfTestKey : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<global::Golden.Fixtures.TestKey>
{
    public SkipListOfTestKey(global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.TestKey>? keyResolver = null,
        global::TC.Tier.Core.Primitives.IKeyComparer<global::Golden.Fixtures.TestKey>? keyComparer = null)
        : base(fs, settings, epoch, keyResolver, keyComparer)
    {
    }

    /// <summary>★ 工厂（异步）：构造 + Initialize(hints) + WaitForReadyAsync 一步到位——hints 注入恢复窗口（缺省空结构首开）；同步 WaitForReady 在异步上下文死锁，异步调用方禁用。</summary>
    public static async global::System.Threading.Tasks.Task<SkipListOfTestKey> CreateAsync(global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.TestKey>? keyResolver = null,
        global::TC.Tier.Core.Primitives.IKeyComparer<global::Golden.Fixtures.TestKey>? keyComparer = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        var index = new SkipListOfTestKey(fs, settings, epoch, keyResolver, keyComparer);
        index.Initialize(hints);
        await index.WaitForReadyAsync(ct);
        return index;
    }
}

