// <auto-generated>[RingKey] 封闭薄类——探测族索引（Hash）（ring-generic-key 设计稿 §2——一行 [RingKey] 声明产出全套封闭形态）</auto-generated>
#pragma warning disable 1591 // 生成封闭形态成员不进 API 文档
#nullable enable

namespace TC.Tier.Runtime.Structures.ProbingIndex;

/// <summary><c>[RingKey(typeof(TestKey))]</c> 探测族封闭薄类——判等闭环硬依赖 IKeyResolver（构造期必注入）。</summary>
public sealed class HashOfTestKey : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<global::Golden.Fixtures.TestKey>
{
    public HashOfTestKey(global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
        global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.TestKey> keyResolver,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Core.Primitives.IKeyComparer<global::Golden.Fixtures.TestKey>? keyComparer = null)
        : base(fs, settings, epoch, keyResolver, keyComparer)
    {
    }

    /// <summary>★ 工厂（异步）：构造 + Initialize(hints) + WaitForReadyAsync 一步到位——hints 注入恢复窗口（缺省空结构首开）；同步 WaitForReady 在异步上下文死锁，异步调用方禁用。</summary>
    public static async global::System.Threading.Tasks.Task<HashOfTestKey> CreateAsync(global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
        global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.TestKey> keyResolver,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Core.Primitives.IKeyComparer<global::Golden.Fixtures.TestKey>? keyComparer = null,
        global::TC.Tier.Runtime.Structures.ProbingIndex.ProbingIndexRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        var index = new HashOfTestKey(fs, settings, keyResolver, epoch, keyComparer);
        index.Initialize(hints);
        await index.WaitForReadyAsync(ct);
        return index;
    }
}

