// <auto-generated>[RingKey] 封闭薄类——Ring（ring-generic-key 设计稿 §2——一行 [RingKey] 声明产出全套封闭形态）</auto-generated>
#pragma warning disable 1591 // 生成封闭形态成员不进 API 文档
#nullable enable

namespace TC.Tier.Runtime.Structures.Ring;

/// <summary><c>[RingKey(typeof(TestKey))]</c> 封闭薄类——开放泛型内核的编译期封闭，消费面只见本类型。</summary>
public sealed class RingOfTestKey : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<global::Golden.Fixtures.TestKey>
{
    public RingOfTestKey(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Contracts.Lifecycle.IRecovery<global::TC.Tier.Runtime.Structures.Ring.RingRecoveryHints>? recovery = null,
        global::TC.Tier.Runtime.Structures.Ring.Contracts.RingCursorFactory<global::TC.Tier.Runtime.Structures.Ring.Contracts.IRingScanCursor>? cursorFactory = null,
        global::TC.Tier.Runtime.Structures.Ring.Contracts.IRingSnapshot? ringSnapshot = null,
        global::TC.Tier.Contracts.Meta.MetaPolicyFactory<global::TC.Tier.Runtime.Structures.Ring.Contracts.RingMetaHeader, global::TC.Tier.Runtime.Structures.Ring.Contracts.RingMetaPayload>? metaPolicyFactory = null,
        global::TC.Tier.Contracts.Meta.IMetaTransport? metaTransport = null,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null)
        : base(settings, fs, recovery, cursorFactory, ringSnapshot, metaPolicyFactory, metaTransport, epoch, logger)
    {
    }

    /// <summary>★ 工厂（异步）：构造 + Initialize(hints) + WaitForReadyAsync 一步到位——hints 注入恢复窗口（缺省空结构首开）；同步 WaitForReady 在异步上下文死锁，异步调用方禁用。</summary>
    public static async global::System.Threading.Tasks.Task<RingOfTestKey> CreateAsync(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Contracts.Lifecycle.IRecovery<global::TC.Tier.Runtime.Structures.Ring.RingRecoveryHints>? recovery = null,
        global::TC.Tier.Runtime.Structures.Ring.Contracts.RingCursorFactory<global::TC.Tier.Runtime.Structures.Ring.Contracts.IRingScanCursor>? cursorFactory = null,
        global::TC.Tier.Runtime.Structures.Ring.Contracts.IRingSnapshot? ringSnapshot = null,
        global::TC.Tier.Contracts.Meta.MetaPolicyFactory<global::TC.Tier.Runtime.Structures.Ring.Contracts.RingMetaHeader, global::TC.Tier.Runtime.Structures.Ring.Contracts.RingMetaPayload>? metaPolicyFactory = null,
        global::TC.Tier.Contracts.Meta.IMetaTransport? metaTransport = null,
        global::TC.Tier.Core.Epochs.LightEpoch? epoch = null,
        global::TC.Tier.Runtime.Structures.Ring.RingRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        var ring = new RingOfTestKey(settings, fs, recovery, cursorFactory, ringSnapshot, metaPolicyFactory, metaTransport, epoch);
        ring.Initialize(hints);
        await ring.WaitForReadyAsync(ct);
        return ring;
    }
}

