<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Runtime -->
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
    <PackageVersion Include="System.IO.Hashing" Version="8.0.0" />
    <!-- Database / Cache -->
    <PackageVersion Include="Microsoft.FASTER.Core" Version="2.6.5" />
    <!-- Code Generation -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
    <!-- Testing -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="Xunit.SkippableFact" Version="1.5.23" />
    <PackageVersion Include="FluentAssertions" Version="6.12.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <!-- Benchmarks (used by non-centralized .csproj, but version defined here for consistency) -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>
</Project>
