<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <PackageReference Include="Microsoft.FASTER.Core" Version="2.6.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TC.Tier.Runtime\TC.Tier.Runtime.csproj" />
    <ProjectReference Include="..\..\src\TC.Tier.Core\TC.Tier.Core.csproj" />
  </ItemGroup>
</Project>
