// <auto-generated>[ConstantRegistry] 区间助手（Zones 声明派生——与常量值同源，spec-12 §10 E3）</auto-generated>
#nullable enable
namespace Golden.Fixtures;

/// <summary>FrameZonesFixture 区间断言——[ConstantRegistry] Zones 派生。</summary>
public static partial class FrameZonesFixture
{
    /// <summary>IsCore：0x0–0xF（区间含端点）。</summary>
    public static bool IsCore(uint value) => value >= 0x0 && value <= 0xF;

    /// <summary>IsEdge：0x10 或 0x20–0x2F（区间含端点）。</summary>
    public static bool IsEdge(uint value) => value == 0x10 || value >= 0x20 && value <= 0x2F;

}
