using System.Text;
using Microsoft.CodeAnalysis;

namespace TC.Tier.CodeGen;

/// <summary>
/// 命令 I/O JSON 契约发射（<see cref="CommandGenerator"/> 产物三——#484）：
/// 每根组产出 JsonContext（自包含实现——零 STJ 接力依赖，#503）与 JsonResults（默认渲染器）。
/// <para>★ JsonContext = 完整 <c>JsonSerializerContext</c> 实现（DefaultJsonTypeInfoResolver 反射解析），
///   **非** partial + [JsonSerializable] 空 partial 形态：真实 SDK 构建里 STJ 生成器的注册序先于
///   本生成器，emitted 声明出现时其扫描已过——空 partial 永不被填充 = CS0534（#503 取证实锤）。
///   代价 = DTO 元数据走运行时反射（trimmed/AOT 下须自行保根 DTO 或自建 JsonSerializerContext
///   经 results/json 参数显式传入覆盖——注入面不变）。</para>
/// </summary>
public sealed partial class CommandGenerator
{
    private static void EmitJsonRoot(SourceProductionContext spc, CommandModel.GroupModel root)
    {
        var rootClass = root.Fqn.Substring(root.Fqn.LastIndexOf('.') + 1);
        var ns = root.Fqn.Contains('.')
            ? root.Fqn.Substring(0, root.Fqn.LastIndexOf('.'))
            : string.Empty;
        var nsPrefix = ns.Length > 0 ? "global::" + ns + "." : string.Empty;
        var envelope = rootClass + "JsonErrorEnvelope";
        var jsonContext = rootClass + "JsonContext";
        var jsonResults = rootClass + "JsonResults";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>" + jsonResults + "——[CommandGroup] " + root.Fqn + " 生成（#484）</auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace " + ns + ";");
        sb.AppendLine(string.Empty);
        sb.AppendLine("/// <summary>命令错误信封（" + jsonResults + " 的 WriteError 默认载荷——#484；" +
            "自定义信封 = 消费方实现 ICommandResults 显式传入覆盖）。</summary>");
        sb.AppendLine("public readonly record struct " + envelope + "(int Code, string Message);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 命令 I/O JSON 契约上下文（命令源生成——#484）：全命令返回类型 + body 类型零登记可用——");
        sb.AppendLine("/// 新增命令零手工步骤。");
        sb.AppendLine("/// <para>★ 自包含实现（#503）：DefaultJsonTypeInfoResolver 反射解析，不经 STJ 源生成接力");
        sb.AppendLine("///   （真实 SDK 构建注册序下 emitted 声明不可达 STJ）。trimmed/AOT 部署请自建");
        sb.AppendLine("///   JsonSerializerContext 经 cli/http 的 json/results 参数显式传入覆盖。</para>");
        sb.AppendLine("/// <para>★ " + rootClass + "Http.TryHandleAsync / " + rootClass + "Cli.Run 的 json/results 参数缺省即消费此上下文。</para>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class " + jsonContext + " : global::System.Text.Json.Serialization.JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver __resolver = new();");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    private static readonly global::System.Text.Json.JsonSerializerOptions __options = CreateOptions();");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    private static global::System.Text.Json.JsonSerializerOptions CreateOptions()");
        sb.AppendLine("    {");
        sb.AppendLine("        var options = new global::System.Text.Json.JsonSerializerOptions();");
        sb.AppendLine("        options.TypeInfoResolver = __resolver;");
        sb.AppendLine("        options.MakeReadOnly();");
        sb.AppendLine("        return options;");
        sb.AppendLine("    }");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <summary>缺省实例（json/results 参数缺省即此）。</summary>");
        sb.AppendLine("    public static " + jsonContext + " Default { get; } = new();");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    private " + jsonContext + "()");
        sb.AppendLine("        : base(null)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <summary>渲染选项（反射解析器——全类型可解析，任意 body/回执类型零登记）。</summary>");
        sb.AppendLine("    public static global::System.Text.Json.JsonSerializerOptions Options => __options;");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions => __options;");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)");
        sb.AppendLine("        => __resolver.GetTypeInfo(type, __options);");
        sb.AppendLine("}");
        sb.AppendLine(string.Empty);
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 默认结果渲染器（命令源生成——#484）：成功载荷与错误信封经 " + jsonContext + " 序列化。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class " + jsonResults + " : global::TC.Tier.CodeGen.ICommandResults");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>缺省实例（results 参数缺省即此）。</summary>");
        sb.AppendLine("    public static " + jsonResults + " Default { get; } = new();");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::System.Threading.Tasks.Task<global::TC.Tier.CodeGen.CommandHttpResponse> WriteAsync<T>(T result)");
        sb.AppendLine("    {");
        sb.AppendLine("        var body = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(result, typeof(T), " + jsonContext + ".Default);");
        sb.AppendLine("        return global::System.Threading.Tasks.Task.FromResult(new global::TC.Tier.CodeGen.CommandHttpResponse");
        sb.AppendLine("        {");
        sb.AppendLine("            Status = 200,");
        sb.AppendLine("            ContentType = \"application/json\",");
        sb.AppendLine("            Body = body,");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::TC.Tier.CodeGen.CommandHttpResponse WriteError(int status, string message)");
        sb.AppendLine("        => Error(status, message);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::TC.Tier.CodeGen.CommandHttpResponse WriteError(int status, global::System.Exception error)");
        sb.AppendLine("        => Error(status, error.Message);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string Render<T>(T result)");
        sb.AppendLine("        => global::System.Text.Json.JsonSerializer.Serialize(result, typeof(T), " + jsonContext + ".Default);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    private static global::TC.Tier.CodeGen.CommandHttpResponse Error(int status, string message)");
        sb.AppendLine("        => new()");
        sb.AppendLine("        {");
        sb.AppendLine("            Status = status,");
        sb.AppendLine("            ContentType = \"application/json\",");
        sb.AppendLine("            Body = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(");
        sb.AppendLine("                new " + nsPrefix + envelope + "(status, message), typeof(" + nsPrefix + envelope + "), " + jsonContext + ".Default),");
        sb.AppendLine("        };");
        sb.AppendLine("}");

        spc.AddSource($"{ns.Replace('.', '_')}_{jsonResults}.g.cs", sb.ToString());
    }
}
