using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TC.Tier.CodeGen;

/// <summary>
/// 命令 I/O JSON 契约发射（<see cref="CommandGenerator"/> 产物三——#484）：
/// 每根组产出 JsonContext（全命令返回类型 + body 类型编译期自动登记）与 JsonResults（默认渲染器）。
/// <para>★ 漏登记回执类型 = 运行时 500 的缺口由生成器单点闭合（#472/#473 输入侧类型化的输出侧对称收口）——
///   新增命令零登记步骤，AOT 契约由生成器维护；消费方自建 context/results 显式传入即覆盖。</para>
/// </summary>
public sealed partial class CommandGenerator
{
    private static void EmitJsonRoot(SourceProductionContext spc, CommandModel.GroupModel root,
        Dictionary<string, CommandModel.GroupModel> byFqn)
    {
        var rootClass = root.Fqn.Substring(root.Fqn.LastIndexOf('.') + 1);
        var ns = root.Fqn.Contains('.')
            ? root.Fqn.Substring(0, root.Fqn.LastIndexOf('.'))
            : string.Empty;
        var nsPrefix = ns.Length > 0 ? "global::" + ns + "." : string.Empty;
        var envelope = rootClass + "JsonErrorEnvelope";
        var jsonContext = rootClass + "JsonContext";
        var jsonResults = rootClass + "JsonResults";

        // 本根子树的 I/O 类型面（byFqn 跨多根——按 ParentFqn 收敛）；
        // 错误信封一并入集（与命令类型同表去重）
        var types = new SortedSet<string>(StringComparer.Ordinal)
        {
            ns.Length > 0 ? ns + "." + envelope : envelope,
        };
        var scope = new HashSet<string>(StringComparer.Ordinal) { root.Fqn };
        var frontier = new Queue<CommandModel.GroupModel>();
        frontier.Enqueue(root);
        while (frontier.Count > 0)
        {
            var group = frontier.Dequeue();
            foreach (var child in byFqn.Values.Where(c => c.ParentFqn == group.Fqn))
            {
                if (scope.Add(child.Fqn)) frontier.Enqueue(child);
            }

            foreach (var command in group.Commands)
            {
                if (command.ResultTypeDisplay.Length > 0) types.Add(command.ResultTypeDisplay);
                foreach (var parameter in command.Params.Where(p => p.Role == CommandModel.ParamRole.Body))
                    types.Add(parameter.TypeOfDisplay);
            }
        }

        var registrations = new StringBuilder();
        foreach (var type in types)
        {
            var qualified = type.Contains('.') ? "global::" + type : type;
            registrations.AppendLine(
                "[global::System.Text.Json.Serialization.JsonSerializable(typeof(" + qualified + "))]");
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>" + jsonResults + "——[CommandGroup] " + root.Fqn + " 生成（#484）</auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace " + ns + ";");
        sb.AppendLine(string.Empty);
        sb.AppendLine("/// <summary>命令错误信封（" + jsonResults + " 的 WriteError 默认载荷——#484；" +
            "自定义信封 = 消费方实现 ICommandResults 显式传入覆盖）。</summary>");
        sb.AppendLine("public readonly record struct " + envelope + "(int Code, string Message);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 命令 I/O JSON 契约上下文（命令源生成——#484）：全命令返回类型 + body 类型编译期自动登记——");
        sb.AppendLine("/// 新增命令零手工步骤，AOT 契约由生成器单点维护。");
        sb.AppendLine("/// <para>★ " + rootClass + "Http.TryHandleAsync / " + rootClass + "Cli.Run 的 json/results 参数缺省即消费此上下文；");
        sb.AppendLine("///   自定义命名策略/错误信封 = 消费方自建 JsonSerializerContext + ICommandResults 显式传入覆盖。</para>");
        sb.AppendLine("/// </summary>");
        sb.Append(registrations);
        sb.AppendLine("internal sealed partial class " + jsonContext + " : global::System.Text.Json.Serialization.JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");
        sb.AppendLine(string.Empty);
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 默认结果渲染器（命令源生成——#484）：成功载荷与错误信封经 " + jsonContext +
            " 源生成序列化（零反射，AOT 契约）。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class " + jsonResults + " : global::TC.Tier.CodeGen.ICommandResults");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>缺省实例（results 参数缺省即此）。</summary>");
        sb.AppendLine("    public static " + jsonResults + " Default { get; } = new();");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::System.Threading.Tasks.Task<global::TC.Tier.CodeGen.CommandHttpResponse> WriteAsync<T>(T result)");
        sb.AppendLine("    {");
        sb.AppendLine("        var body = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(result, typeof(T), " + jsonContext + ".Default);");
        sb.AppendLine("        return global::System.Threading.Tasks.Task.FromResult(new global::TC.Tier.CodeGen.CommandHttpResponse");
        sb.AppendLine("        {");
        sb.AppendLine("            Status = 200,");
        sb.AppendLine("            ContentType = \"application/json\",");
        sb.AppendLine("            Body = body,");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::TC.Tier.CodeGen.CommandHttpResponse WriteError(int status, string message)");
        sb.AppendLine("        => Error(status, message);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public global::TC.Tier.CodeGen.CommandHttpResponse WriteError(int status, global::System.Exception error)");
        sb.AppendLine("        => Error(status, error.Message);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public string Render<T>(T result)");
        sb.AppendLine("        => global::System.Text.Json.JsonSerializer.Serialize(result, typeof(T), " + jsonContext + ".Default);");
        sb.AppendLine(string.Empty);
        sb.AppendLine("    private static global::TC.Tier.CodeGen.CommandHttpResponse Error(int status, string message)");
        sb.AppendLine("        => new()");
        sb.AppendLine("        {");
        sb.AppendLine("            Status = status,");
        sb.AppendLine("            ContentType = \"application/json\",");
        sb.AppendLine("            Body = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(");
        sb.AppendLine("                new " + nsPrefix + envelope + "(status, message), typeof(" + nsPrefix + envelope + "), " + jsonContext + ".Default),");
        sb.AppendLine("        };");
        sb.AppendLine("}");

        spc.AddSource($"{ns.Replace('.', '_')}_{jsonResults}.g.cs", sb.ToString());
    }
}
