// <auto-generated>[WireArray] 变长集合线编码（spec-12 §10 E1——[定长前缀][Count 4B][item×N]；位置由声明序累积，字节序收口本生成物）</auto-generated>
#nullable enable
using System;   // 生成文件自足——不依赖消费方的 ImplicitUsings（MemoryExtensions.CopyTo 等扩展）
using System.Buffers;
using System.Buffers.Binary;
namespace Golden.Fixtures;

/// <summary>IdBatch 变长线编码——[WireArray] 派生（MaxCount=32；布局=字段声明序）。</summary>
public static class IdBatchCodec
{
    /// <summary>防御上限（标注同源——消费层超限判定用）。</summary>
    public const int MaxCount = 32;


    /// <summary>编码（便捷形态——缓冲自配；返回新数组）。</summary>
    public static byte[] Encode(in IdBatch value)
    {
        var buf = new byte[4 + 4 + value.Ids.Length * 4];
        Encode(buf, in value);
        return buf;
    }


    /// <summary>编码（[前缀][Count 4B][item×N]）。返回写入长度。</summary>
    public static int Encode(System.Span<byte> dest, in IdBatch value)
    {
        int cursor = 0;
        BinaryPrimitives.WriteUInt32LittleEndian(dest[cursor..], value.Batch);
        cursor += 4;
        int count = value.Ids.Length;
        int total = cursor + 4 + count * 4;
        if (dest.Length < total)
            throw new System.ArgumentException($"Buffer too small: {dest.Length} < {total}", nameof(dest));
        BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], count);
        cursor += 4;
        foreach (var item in value.Ids)
        {
            BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], item);
            cursor += 4;
        }
        return total;
    }


    /// <summary>编码到池化租借缓冲（零分配热路径——返回写入长度；缓冲由调用方
    /// <c>ArrayPool&lt;byte&gt;.Shared.Return(rented)</c> 归还。载荷经传输同步拷贝入帧后即可归还）。</summary>
    public static int EncodePooled(in IdBatch value, out byte[] rented)
    {
        var len = ComputeLength(in value);
        rented = ArrayPool<byte>.Shared.Rent(len);
        Encode(rented.AsSpan(0, len), in value);
        return len;
    }


    /// <summary>编码到 <see cref="System.Buffers.IBufferWriter{Byte}"/>（零拷贝汇——PipeWriter 直写形态）。</summary>
    public static void Encode(System.Buffers.IBufferWriter<byte> writer, in IdBatch value)
    {
        var len = ComputeLength(in value);
        var span = writer.GetSpan(len);
        Encode(span, in value);
        writer.Advance(len);
    }


    /// <summary>总长（前缀 + Count 4B + 项区——池化/直写形态的长度预算口）。</summary>
    public static int ComputeLength(in IdBatch value)
        => 4 + 4 + value.Ids.Length * 4;


    /// <summary>解码（截断/Count 超上限（&gt;32）= false——畸形报文拦截；逐字段防御）。</summary>
    public static bool TryDecode(System.ReadOnlySpan<byte> source, out IdBatch value)
    {
        value = default;
        int cursor = 0;
        if (source.Length < cursor + 4) return false;
        var batch = BinaryPrimitives.ReadUInt32LittleEndian(source[cursor..].Slice(0, 4));
        cursor += 4;
        if (source.Length < cursor + 4) return false;
        int count = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]);
        if ((uint)count > 32) return false;   // 负数经无符号比较一并拦截
        if (source.Length < cursor + 4 + count * 4) return false;
        cursor += 4;
        var items = new int[count];
        for (int i = 0; i < count; i++)
        {
            items[i] = BinaryPrimitives.ReadInt32LittleEndian(source.Slice(cursor, 4).Slice(0, 4));
            cursor += 4;
        }
        value = new IdBatch(batch, items);
        return true;
    }

}
