// <auto-generated>[WireArray] 变长集合线编码（spec-12 §10 E1——[定长前缀][Count 4B][item×N]；位置由声明序累积，字节序收口本生成物）</auto-generated>
#nullable enable
using System;   // 生成文件自足——不依赖消费方的 ImplicitUsings（MemoryExtensions.CopyTo 等扩展）
using System.Buffers;
using System.Buffers.Binary;
namespace Golden.Fixtures;

/// <summary>ItemPack 变长线编码——[WireArray] 派生（MaxCount=16；布局=字段声明序）。</summary>
public static class ItemPackCodec
{
    /// <summary>防御上限（标注同源——消费层超限判定用）。</summary>
    public const int MaxCount = 16;


    /// <summary>编码（便捷形态——缓冲自配；返回新数组）。</summary>
    public static byte[] Encode(in ItemPack value)
    {
        var buf = new byte[8 + 4 + value.Items.Length * Golden.Fixtures.ItemCodec.StructSize];
        Encode(buf, in value);
        return buf;
    }


    /// <summary>编码（[前缀][Count 4B][item×N]）。返回写入长度。</summary>
    public static int Encode(System.Span<byte> dest, in ItemPack value)
    {
        int cursor = 0;
        BinaryPrimitives.WriteUInt64LittleEndian(dest[cursor..], value.PackId);
        cursor += 8;
        int count = value.Items.Length;
        int total = cursor + 4 + count * Golden.Fixtures.ItemCodec.StructSize;
        if (dest.Length < total)
            throw new System.ArgumentException($"Buffer too small: {dest.Length} < {total}", nameof(dest));
        BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], count);
        cursor += 4;
        foreach (var item in value.Items)
        {
            Golden.Fixtures.ItemCodec.Write(dest[cursor..], item);
            cursor += Golden.Fixtures.ItemCodec.StructSize;
        }
        return total;
    }


    /// <summary>编码到池化租借缓冲（零分配热路径——返回写入长度；缓冲由调用方
    /// <c>ArrayPool&lt;byte&gt;.Shared.Return(rented)</c> 归还。载荷经传输同步拷贝入帧后即可归还）。</summary>
    public static int EncodePooled(in ItemPack value, out byte[] rented)
    {
        var len = ComputeLength(in value);
        rented = ArrayPool<byte>.Shared.Rent(len);
        Encode(rented.AsSpan(0, len), in value);
        return len;
    }


    /// <summary>编码到 <see cref="System.Buffers.IBufferWriter{Byte}"/>（零拷贝汇——PipeWriter 直写形态）。</summary>
    public static void Encode(System.Buffers.IBufferWriter<byte> writer, in ItemPack value)
    {
        var len = ComputeLength(in value);
        var span = writer.GetSpan(len);
        Encode(span, in value);
        writer.Advance(len);
    }


    /// <summary>总长（前缀 + Count 4B + 项区——池化/直写形态的长度预算口）。</summary>
    public static int ComputeLength(in ItemPack value)
        => 8 + 4 + value.Items.Length * Golden.Fixtures.ItemCodec.StructSize;


    /// <summary>解码（截断/Count 超上限（&gt;16）= false——畸形报文拦截；逐字段防御）。</summary>
    public static bool TryDecode(System.ReadOnlySpan<byte> source, out ItemPack value)
    {
        value = default;
        int cursor = 0;
        if (source.Length < cursor + 8) return false;
        var packId = BinaryPrimitives.ReadUInt64LittleEndian(source[cursor..].Slice(0, 8));
        cursor += 8;
        if (source.Length < cursor + 4) return false;
        int count = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]);
        if ((uint)count > 16) return false;   // 负数经无符号比较一并拦截
        if (source.Length < cursor + 4 + count * Golden.Fixtures.ItemCodec.StructSize) return false;
        cursor += 4;
        var items = new Golden.Fixtures.Item[count];
        for (int i = 0; i < count; i++)
        {
            items[i] = Golden.Fixtures.ItemCodec.Read(source.Slice(cursor, Golden.Fixtures.ItemCodec.StructSize));
            cursor += Golden.Fixtures.ItemCodec.StructSize;
        }
        value = new ItemPack(packId, items);
        return true;
    }

}
