// <auto-generated>[WireArray] 变长集合线编码（spec-12 §10 E1——[定长前缀][Count 4B][item×N]；位置由声明序累积，字节序收口本生成物）</auto-generated>
#nullable enable
using System;   // 生成文件自足——不依赖消费方的 ImplicitUsings（MemoryExtensions.CopyTo 等扩展）
using System.Buffers;
using System.Buffers.Binary;
namespace Golden.Fixtures;

/// <summary>BytesPayload 变长线编码——[WireArray] 派生（MaxCount=64；布局=字段声明序）。</summary>
public static class BytesPayloadCodec
{
    /// <summary>防御上限（标注同源——消费层超限判定用）。</summary>
    public const int MaxCount = 64;


    /// <summary>编码（便捷形态——缓冲自配；返回新数组）。</summary>
    public static byte[] Encode(in BytesPayload value)
    {
        var buf = new byte[1 + 4 + value.Detail.Length * 1];
        Encode(buf, in value);
        return buf;
    }


    /// <summary>编码（[前缀][Count 4B][item×N]）。返回写入长度。</summary>
    public static int Encode(System.Span<byte> dest, in BytesPayload value)
    {
        int cursor = 0;
        { var d = dest[cursor..]; d[0] = value.Code; }
        cursor += 1;
        int count = value.Detail.Length;
        int total = cursor + 4 + count * 1;
        if (dest.Length < total)
            throw new System.ArgumentException($"Buffer too small: {dest.Length} < {total}", nameof(dest));
        BinaryPrimitives.WriteInt32LittleEndian(dest[cursor..], count);
        cursor += 4;
        value.Detail.CopyTo(dest[cursor..]);
        return total;
    }


    /// <summary>编码到池化租借缓冲（零分配热路径——返回写入长度；缓冲由调用方
    /// <c>ArrayPool&lt;byte&gt;.Shared.Return(rented)</c> 归还。载荷经传输同步拷贝入帧后即可归还）。</summary>
    public static int EncodePooled(in BytesPayload value, out byte[] rented)
    {
        var len = ComputeLength(in value);
        rented = ArrayPool<byte>.Shared.Rent(len);
        Encode(rented.AsSpan(0, len), in value);
        return len;
    }


    /// <summary>编码到 <see cref="System.Buffers.IBufferWriter{Byte}"/>（零拷贝汇——PipeWriter 直写形态）。</summary>
    public static void Encode(System.Buffers.IBufferWriter<byte> writer, in BytesPayload value)
    {
        var len = ComputeLength(in value);
        var span = writer.GetSpan(len);
        Encode(span, in value);
        writer.Advance(len);
    }


    /// <summary>总长（前缀 + Count 4B + 项区——池化/直写形态的长度预算口）。</summary>
    public static int ComputeLength(in BytesPayload value)
        => 1 + 4 + value.Detail.Length * 1;


    /// <summary>解码（截断/Count 超上限（&gt;64）= false——畸形报文拦截；逐字段防御）。</summary>
    public static bool TryDecode(System.ReadOnlySpan<byte> source, out BytesPayload value)
    {
        value = default;
        int cursor = 0;
        if (source.Length < cursor + 1) return false;
        var code = source[cursor..][0];
        cursor += 1;
        if (source.Length < cursor + 4) return false;
        int count = BinaryPrimitives.ReadInt32LittleEndian(source[cursor..]);
        if ((uint)count > 64) return false;   // 负数经无符号比较一并拦截
        if (source.Length < cursor + 4 + count * 1) return false;
        cursor += 4;
        var items = source.Slice(cursor, count).ToArray();
        value = new BytesPayload(code, items);
        return true;
    }

}
