// <auto-generated>类型化 DSL（[SpecParam] 派生——spec-typed-frontend §4 P-b；TierSpec 属性集 = 方法集）</auto-generated>
#nullable enable
namespace TC.Tier.Core.IO;

/// <summary>spec 构造 DSL（L2 编译期安全层）——非法参数×介质不可写出；ToString = spec 字符串。</summary>
public static class Specs
{
    /// <summary>本地文件系统根（'/…' 绝对 / 其他相对 CWD 形态）。</summary>
    public static LocalSpec Local(string root)
        => new(TierSpec.Parse(root.StartsWith('/') ? $"local://{root}" : root.StartsWith(System.IO.Path.DirectorySeparatorChar) || (root.Length > 1 && root[1] == ':') ? $"local:///{root}" : $"local:{root}"));

    /// <summary>内存文件系统（私有卷——全挂载参数可链）。</summary>
    public static MemorySpec Memory() => new(TierSpec.Parse("memory:"));

    /// <summary>虚拟文件系统载体路径（'/dev/…' 首段制设备形态）。</summary>
    public static VirtualSpec Virtual(string path) => new(TierSpec.Parse($"virtual://{path}"));

    /// <summary>网络文件系统（s3：endpoint[:port] / bucket / key 前缀）。</summary>
    public static NetworkSpec Network(string endpoint, string bucket, string keyPrefix = "")
        => new(TierSpec.Parse($"network:///s3/{endpoint}/{bucket}/{keyPrefix}"));
}

/// <summary>local:// spec 构造器——With 方法集 = [SpecParam] 派生（TierSpec 属性面）。</summary>
public sealed class LocalSpec
{
    private TierSpec _spec;
    internal LocalSpec(TierSpec spec) => _spec = spec;
    /// <summary>Label——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public LocalSpec Label(string value)
    {
        _spec = _spec with { Label = value };
        return this;
    }
    /// <summary>Quota——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public LocalSpec Quota(long bytes)
    {
        _spec = _spec with { QuotaBytes = bytes };
        return this;
    }
    /// <summary>Access——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public LocalSpec Access(AccessMode mode)
    {
        _spec = _spec with { Access = mode };
        return this;
    }
    /// <summary>只读挂载糖（access=ro）。</summary>
    public LocalSpec ReadOnly() => Access(AccessMode.Read);
    /// <summary>纯摄入挂载糖（access=wo）。</summary>
    public LocalSpec WriteOnly() => Access(AccessMode.Write);
    /// <summary>spec 字符串（TierSpec 序列化——与解析器同源）。</summary>
    public override string ToString() => _spec.ToString();
    /// <summary>解析形态（TierSpec——与 ToString 同源）。</summary>
    public TierSpec ToSpec() => _spec;
}

/// <summary>memory: spec 构造器——With 方法集 = [SpecParam] 派生（TierSpec 属性面）。</summary>
public sealed class MemorySpec
{
    private TierSpec _spec;
    internal MemorySpec(TierSpec spec) => _spec = spec;
    /// <summary>Label——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public MemorySpec Label(string value)
    {
        _spec = _spec with { Label = value };
        return this;
    }
    /// <summary>Quota——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public MemorySpec Quota(long bytes)
    {
        _spec = _spec with { QuotaBytes = bytes };
        return this;
    }
    /// <summary>只读挂载糖（access=ro）。</summary>
    public MemorySpec ReadOnly() => Access(AccessMode.Read);
    /// <summary>纯摄入挂载糖（access=wo）。</summary>
    public MemorySpec WriteOnly() => Access(AccessMode.Write);
    /// <summary>spec 字符串（TierSpec 序列化——与解析器同源）。</summary>
    public override string ToString() => _spec.ToString();
    /// <summary>解析形态（TierSpec——与 ToString 同源）。</summary>
    public TierSpec ToSpec() => _spec;
}

/// <summary>virtual:// spec 构造器——With 方法集 = [SpecParam] 派生（TierSpec 属性面）。</summary>
public sealed class VirtualSpec
{
    private TierSpec _spec;
    internal VirtualSpec(TierSpec spec) => _spec = spec;
    /// <summary>Label——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public VirtualSpec Label(string value)
    {
        _spec = _spec with { Label = value };
        return this;
    }
    /// <summary>Quota——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public VirtualSpec Quota(long bytes)
    {
        _spec = _spec with { QuotaBytes = bytes };
        return this;
    }
    /// <summary>只读挂载糖（access=ro）。</summary>
    public VirtualSpec ReadOnly() => Access(AccessMode.Read);
    /// <summary>纯摄入挂载糖（access=wo）。</summary>
    public VirtualSpec WriteOnly() => Access(AccessMode.Write);
    /// <summary>spec 字符串（TierSpec 序列化——与解析器同源）。</summary>
    public override string ToString() => _spec.ToString();
    /// <summary>解析形态（TierSpec——与 ToString 同源）。</summary>
    public TierSpec ToSpec() => _spec;
}

/// <summary>network:///s3 spec 构造器——With 方法集 = [SpecParam] 派生（TierSpec 属性面）。</summary>
public sealed class NetworkSpec
{
    private TierSpec _spec;
    internal NetworkSpec(TierSpec spec) => _spec = spec;
    /// <summary>Label——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public NetworkSpec Label(string value)
    {
        _spec = _spec with { Label = value };
        return this;
    }
    /// <summary>Quota——spec 属性链式设置（[SpecParam] 派生；返回本构造器）。</summary>
    public NetworkSpec Quota(long bytes)
    {
        _spec = _spec with { QuotaBytes = bytes };
        return this;
    }
    /// <summary>只读挂载糖（access=ro）。</summary>
    public NetworkSpec ReadOnly() => Access(AccessMode.Read);
    /// <summary>纯摄入挂载糖（access=wo）。</summary>
    public NetworkSpec WriteOnly() => Access(AccessMode.Write);
    /// <summary>spec 字符串（TierSpec 序列化——与解析器同源）。</summary>
    public override string ToString() => _spec.ToString();
    /// <summary>解析形态（TierSpec——与 ToString 同源）。</summary>
    public TierSpec ToSpec() => _spec;
}

