// <auto-generated>network 协议注册（[NetworkProtocol] 派生——spec-typed-frontend §4 P-c）</auto-generated>
#nullable enable

internal static class TierFsProtocolModule
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void RegisterProtocols()
    {
        global::TC.Tier.Core.IO.TierFs.RegisterProtocol("fakeproto", new global::Golden.Fixtures.FakeProtocolBuilder());
    }
}
