// <auto-generated>TierFs 类型化重载族（[MediumOptions] 派生——spec-typed-frontend §4 P-a）</auto-generated>
#nullable enable
namespace TC.Tier.Core.IO;

public static partial class TierFs
{
    /// <summary>New——类型化重载（[MediumOptions("local")] 派生；options 调优字段全量采用）。</summary>
    public static IFileSystem New(string spec, Golden.Fixtures.FakeOptions options, ILogger? logger = null)
        => Build(TierSpec.Parse(spec), options, TierFsVerb.New, logger, StorageNature.Local, "FakeOptions");

    /// <summary>Open——类型化重载（[MediumOptions("local")] 派生；options 调优字段全量采用）。</summary>
    public static IFileSystem Open(string spec, Golden.Fixtures.FakeOptions options, ILogger? logger = null)
        => Build(TierSpec.Parse(spec), options, TierFsVerb.Open, logger, StorageNature.Local, "FakeOptions");

}
