// <auto-generated>外部 [NetworkProtocol] 注册桥——消费方程序集加载即注册（源生成器，零反射，NativeAOT 安全）</auto-generated>
#nullable enable

internal static class TierFsExternalProtocolRegistration
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        global::TC.Tier.Core.IO.TierFs.RegisterProtocol("extproto", new global::Golden.External.ExtProtocolBuilder());
    }
}
