// <auto-generated>[KvStore] 封闭形态——TierKv 产品类（formatter 零代码 + 默认装配）</auto-generated>
#pragma warning disable 1591 // 生成封闭形态成员不进 API 文档
#nullable enable

namespace TC.Tier.Products.Kv;

/// <summary><c>[KvStore(typeof(OrderKey), typeof(Position))]</c> 封闭形态——开放泛型产品类的编译期封闭（[RingKey] 同款先例），消费面只见本类型；formatter 按 TValue 自动发射（D6/D7）。</summary>
public sealed class TierKvOfOrderKeyPosition : global::TC.Tier.Products.Kv.TierKv<global::Golden.Fixtures.OrderKey, global::Golden.Fixtures.Position>
{
    private static readonly global::TC.Tier.Products.Kv.TierKvOptions s_defaultOptions = global::TC.Tier.Products.Kv.TierKvOptions.Default;

    private static readonly global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Position> s_formatter = global::TC.Tier.Products.Kv.ValueFormatters.Blittable<global::Golden.Fixtures.Position>();

    public TierKvOfOrderKeyPosition(global::TC.Tier.Runtime.Structures.Ring.RingBase<global::Golden.Fixtures.OrderKey> ring,
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index,
        global::TC.Tier.Products.Kv.TierKvOptions options,
        global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Position> formatter,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex = null)
        : base(ring, index, options, formatter, logger, rangeIndex)
    {
    }

    /// <summary>★ 工厂（异步）：默认装配（Ring + 索引按 Options.IndexKind 路由，Settings 经 TierKvAssembly 翻译）+ Initialize + WaitForReadyAsync 一步到位；options/formatter 显式注入胜出。</summary>
    public static async global::System.Threading.Tasks.Task<TierKvOfOrderKeyPosition> CreateAsync(
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Products.Kv.TierKvOptions? options = null,
        global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Position>? formatter = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Products.Kv.KvRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        options ??= s_defaultOptions;
        var ring = new RingImpl(global::TC.Tier.Products.Kv.TierKvAssembly.RingSettings(fs, options), fs);
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index = options.IndexKind switch
        {
            global::TC.Tier.Products.Kv.KvIndexKind.Hash => new HashIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.HashSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.BTree => new BTreeIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.BTreeSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.SkipList => new SkipListIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.SkipListSettings(fs, options), ring),
            _ => throw new global::System.ArgumentOutOfRangeException(
                nameof(options), options.IndexKind, "未知主索引类型"),
        };
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex =
            options.EnableRangeIndex
                ? global::TC.Tier.Products.Kv.TierKvAssembly.CreateRangeIndex(fs, options, ring)
                : null;
        var kv = new TierKvOfOrderKeyPosition(ring, index, options, formatter ?? s_formatter, logger, rangeIndex);
        kv.Initialize(hints);
        await kv.WaitForReadyAsync(ct).ConfigureAwait(false);
        return kv;
    }

    /// <summary>内嵌 Ring 派生实现——派生肢获得 protected internal 构造权（开放泛型零构造，同 RingOfT 形态）。</summary>
    private sealed class RingImpl : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<global::Golden.Fixtures.OrderKey>
    {
        public RingImpl(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
            global::TC.Tier.Core.IO.IFileSystem fs)
            : base(settings, fs)
        {
        }
    }

    /// <summary>内嵌探测族派生实现——resolver 挂 Ring 本体（tag 判等闭环回读数据面）。</summary>
    private sealed class HashIndexImpl : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<global::Golden.Fixtures.OrderKey>
    {
        public HashIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（BTree）——resolver 挂 Ring 本体。</summary>
    private sealed class BTreeIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<global::Golden.Fixtures.OrderKey>
    {
        public BTreeIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（SkipList）——resolver 挂 Ring 本体。</summary>
    private sealed class SkipListIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<global::Golden.Fixtures.OrderKey>
    {
        public SkipListIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }
}
/// <summary><c>[KvStore(typeof(OrderKey), typeof(Byte))]</c> 封闭形态——开放泛型产品类的编译期封闭（[RingKey] 同款先例），消费面只见本类型；formatter 按 TValue 自动发射（D6/D7）。</summary>
public sealed class TierKvOfOrderKeyByte : global::TC.Tier.Products.Kv.TierKv<global::Golden.Fixtures.OrderKey, byte>
{
    private static readonly global::TC.Tier.Products.Kv.TierKvOptions s_defaultOptions = global::TC.Tier.Products.Kv.TierKvOptions.Default;

    private static readonly global::TC.Tier.Products.Kv.IValueFormatter<byte> s_formatter = global::TC.Tier.Products.Kv.ValueFormatters.Byte;

    public TierKvOfOrderKeyByte(global::TC.Tier.Runtime.Structures.Ring.RingBase<global::Golden.Fixtures.OrderKey> ring,
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index,
        global::TC.Tier.Products.Kv.TierKvOptions options,
        global::TC.Tier.Products.Kv.IValueFormatter<byte> formatter,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex = null)
        : base(ring, index, options, formatter, logger, rangeIndex)
    {
    }

    /// <summary>★ 工厂（异步）：默认装配（Ring + 索引按 Options.IndexKind 路由，Settings 经 TierKvAssembly 翻译）+ Initialize + WaitForReadyAsync 一步到位；options/formatter 显式注入胜出。</summary>
    public static async global::System.Threading.Tasks.Task<TierKvOfOrderKeyByte> CreateAsync(
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Products.Kv.TierKvOptions? options = null,
        global::TC.Tier.Products.Kv.IValueFormatter<byte>? formatter = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Products.Kv.KvRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        options ??= s_defaultOptions;
        var ring = new RingImpl(global::TC.Tier.Products.Kv.TierKvAssembly.RingSettings(fs, options), fs);
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index = options.IndexKind switch
        {
            global::TC.Tier.Products.Kv.KvIndexKind.Hash => new HashIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.HashSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.BTree => new BTreeIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.BTreeSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.SkipList => new SkipListIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.SkipListSettings(fs, options), ring),
            _ => throw new global::System.ArgumentOutOfRangeException(
                nameof(options), options.IndexKind, "未知主索引类型"),
        };
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex =
            options.EnableRangeIndex
                ? global::TC.Tier.Products.Kv.TierKvAssembly.CreateRangeIndex(fs, options, ring)
                : null;
        var kv = new TierKvOfOrderKeyByte(ring, index, options, formatter ?? s_formatter, logger, rangeIndex);
        kv.Initialize(hints);
        await kv.WaitForReadyAsync(ct).ConfigureAwait(false);
        return kv;
    }

    /// <summary>内嵌 Ring 派生实现——派生肢获得 protected internal 构造权（开放泛型零构造，同 RingOfT 形态）。</summary>
    private sealed class RingImpl : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<global::Golden.Fixtures.OrderKey>
    {
        public RingImpl(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
            global::TC.Tier.Core.IO.IFileSystem fs)
            : base(settings, fs)
        {
        }
    }

    /// <summary>内嵌探测族派生实现——resolver 挂 Ring 本体（tag 判等闭环回读数据面）。</summary>
    private sealed class HashIndexImpl : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<global::Golden.Fixtures.OrderKey>
    {
        public HashIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（BTree）——resolver 挂 Ring 本体。</summary>
    private sealed class BTreeIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<global::Golden.Fixtures.OrderKey>
    {
        public BTreeIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（SkipList）——resolver 挂 Ring 本体。</summary>
    private sealed class SkipListIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<global::Golden.Fixtures.OrderKey>
    {
        public SkipListIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }
}
/// <summary><c>[KvStore(typeof(OrderKey), typeof(byte[]))]</c> 封闭形态——开放泛型产品类的编译期封闭（[RingKey] 同款先例），消费面只见本类型；formatter 按 TValue 自动发射（D6/D7）。</summary>
public sealed class TierKvOfOrderKeyByteArray : global::TC.Tier.Products.Kv.TierKv<global::Golden.Fixtures.OrderKey, byte[]>
{
    private static readonly global::TC.Tier.Products.Kv.TierKvOptions s_defaultOptions = global::TC.Tier.Products.Kv.TierKvOptions.Default;

    private static readonly global::TC.Tier.Products.Kv.IValueFormatter<byte[]> s_formatter = global::TC.Tier.Products.Kv.ValueFormatters.ByteArray;

    public TierKvOfOrderKeyByteArray(global::TC.Tier.Runtime.Structures.Ring.RingBase<global::Golden.Fixtures.OrderKey> ring,
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index,
        global::TC.Tier.Products.Kv.TierKvOptions options,
        global::TC.Tier.Products.Kv.IValueFormatter<byte[]> formatter,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex = null)
        : base(ring, index, options, formatter, logger, rangeIndex)
    {
    }

    /// <summary>★ 工厂（异步）：默认装配（Ring + 索引按 Options.IndexKind 路由，Settings 经 TierKvAssembly 翻译）+ Initialize + WaitForReadyAsync 一步到位；options/formatter 显式注入胜出。</summary>
    public static async global::System.Threading.Tasks.Task<TierKvOfOrderKeyByteArray> CreateAsync(
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Products.Kv.TierKvOptions? options = null,
        global::TC.Tier.Products.Kv.IValueFormatter<byte[]>? formatter = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Products.Kv.KvRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        options ??= s_defaultOptions;
        var ring = new RingImpl(global::TC.Tier.Products.Kv.TierKvAssembly.RingSettings(fs, options), fs);
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index = options.IndexKind switch
        {
            global::TC.Tier.Products.Kv.KvIndexKind.Hash => new HashIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.HashSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.BTree => new BTreeIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.BTreeSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.SkipList => new SkipListIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.SkipListSettings(fs, options), ring),
            _ => throw new global::System.ArgumentOutOfRangeException(
                nameof(options), options.IndexKind, "未知主索引类型"),
        };
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex =
            options.EnableRangeIndex
                ? global::TC.Tier.Products.Kv.TierKvAssembly.CreateRangeIndex(fs, options, ring)
                : null;
        var kv = new TierKvOfOrderKeyByteArray(ring, index, options, formatter ?? s_formatter, logger, rangeIndex);
        kv.Initialize(hints);
        await kv.WaitForReadyAsync(ct).ConfigureAwait(false);
        return kv;
    }

    /// <summary>内嵌 Ring 派生实现——派生肢获得 protected internal 构造权（开放泛型零构造，同 RingOfT 形态）。</summary>
    private sealed class RingImpl : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<global::Golden.Fixtures.OrderKey>
    {
        public RingImpl(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
            global::TC.Tier.Core.IO.IFileSystem fs)
            : base(settings, fs)
        {
        }
    }

    /// <summary>内嵌探测族派生实现——resolver 挂 Ring 本体（tag 判等闭环回读数据面）。</summary>
    private sealed class HashIndexImpl : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<global::Golden.Fixtures.OrderKey>
    {
        public HashIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（BTree）——resolver 挂 Ring 本体。</summary>
    private sealed class BTreeIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<global::Golden.Fixtures.OrderKey>
    {
        public BTreeIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（SkipList）——resolver 挂 Ring 本体。</summary>
    private sealed class SkipListIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<global::Golden.Fixtures.OrderKey>
    {
        public SkipListIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }
}
/// <summary><c>[KvStore(typeof(OrderKey), typeof(ReadOnlyMemory))]</c> 封闭形态——开放泛型产品类的编译期封闭（[RingKey] 同款先例），消费面只见本类型；formatter 按 TValue 自动发射（D6/D7）。</summary>
public sealed class TierKvOfOrderKeyReadOnlyMemory : global::TC.Tier.Products.Kv.TierKv<global::Golden.Fixtures.OrderKey, global::System.ReadOnlyMemory<byte>>
{
    private static readonly global::TC.Tier.Products.Kv.TierKvOptions s_defaultOptions = global::TC.Tier.Products.Kv.TierKvOptions.Default;

    private static readonly global::TC.Tier.Products.Kv.IValueFormatter<global::System.ReadOnlyMemory<byte>> s_formatter = global::TC.Tier.Products.Kv.ValueFormatters.ByteMemory;

    public TierKvOfOrderKeyReadOnlyMemory(global::TC.Tier.Runtime.Structures.Ring.RingBase<global::Golden.Fixtures.OrderKey> ring,
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index,
        global::TC.Tier.Products.Kv.TierKvOptions options,
        global::TC.Tier.Products.Kv.IValueFormatter<global::System.ReadOnlyMemory<byte>> formatter,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex = null)
        : base(ring, index, options, formatter, logger, rangeIndex)
    {
    }

    /// <summary>★ 工厂（异步）：默认装配（Ring + 索引按 Options.IndexKind 路由，Settings 经 TierKvAssembly 翻译）+ Initialize + WaitForReadyAsync 一步到位；options/formatter 显式注入胜出。</summary>
    public static async global::System.Threading.Tasks.Task<TierKvOfOrderKeyReadOnlyMemory> CreateAsync(
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Products.Kv.TierKvOptions? options = null,
        global::TC.Tier.Products.Kv.IValueFormatter<global::System.ReadOnlyMemory<byte>>? formatter = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Products.Kv.KvRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        options ??= s_defaultOptions;
        var ring = new RingImpl(global::TC.Tier.Products.Kv.TierKvAssembly.RingSettings(fs, options), fs);
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index = options.IndexKind switch
        {
            global::TC.Tier.Products.Kv.KvIndexKind.Hash => new HashIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.HashSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.BTree => new BTreeIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.BTreeSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.SkipList => new SkipListIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.SkipListSettings(fs, options), ring),
            _ => throw new global::System.ArgumentOutOfRangeException(
                nameof(options), options.IndexKind, "未知主索引类型"),
        };
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex =
            options.EnableRangeIndex
                ? global::TC.Tier.Products.Kv.TierKvAssembly.CreateRangeIndex(fs, options, ring)
                : null;
        var kv = new TierKvOfOrderKeyReadOnlyMemory(ring, index, options, formatter ?? s_formatter, logger, rangeIndex);
        kv.Initialize(hints);
        await kv.WaitForReadyAsync(ct).ConfigureAwait(false);
        return kv;
    }

    /// <summary>内嵌 Ring 派生实现——派生肢获得 protected internal 构造权（开放泛型零构造，同 RingOfT 形态）。</summary>
    private sealed class RingImpl : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<global::Golden.Fixtures.OrderKey>
    {
        public RingImpl(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
            global::TC.Tier.Core.IO.IFileSystem fs)
            : base(settings, fs)
        {
        }
    }

    /// <summary>内嵌探测族派生实现——resolver 挂 Ring 本体（tag 判等闭环回读数据面）。</summary>
    private sealed class HashIndexImpl : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<global::Golden.Fixtures.OrderKey>
    {
        public HashIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（BTree）——resolver 挂 Ring 本体。</summary>
    private sealed class BTreeIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<global::Golden.Fixtures.OrderKey>
    {
        public BTreeIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（SkipList）——resolver 挂 Ring 本体。</summary>
    private sealed class SkipListIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<global::Golden.Fixtures.OrderKey>
    {
        public SkipListIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }
}
/// <summary><c>[KvStore(typeof(OrderKey), typeof(Payload))]</c> 封闭形态——开放泛型产品类的编译期封闭（[RingKey] 同款先例），消费面只见本类型；formatter 按 TValue 自动发射（D6/D7）。</summary>
public sealed class TierKvOfOrderKeyPayload : global::TC.Tier.Products.Kv.TierKv<global::Golden.Fixtures.OrderKey, global::Golden.Fixtures.Payload>
{
    private static readonly global::TC.Tier.Products.Kv.TierKvOptions s_defaultOptions = global::TC.Tier.Products.Kv.TierKvOptions.Default;

    private static readonly global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Payload> s_formatter = new global::Golden.Fixtures.PayloadFormatter();

    public TierKvOfOrderKeyPayload(global::TC.Tier.Runtime.Structures.Ring.RingBase<global::Golden.Fixtures.OrderKey> ring,
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index,
        global::TC.Tier.Products.Kv.TierKvOptions options,
        global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Payload> formatter,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex = null)
        : base(ring, index, options, formatter, logger, rangeIndex)
    {
    }

    /// <summary>★ 工厂（异步）：默认装配（Ring + 索引按 Options.IndexKind 路由，Settings 经 TierKvAssembly 翻译）+ Initialize + WaitForReadyAsync 一步到位；options/formatter 显式注入胜出。</summary>
    public static async global::System.Threading.Tasks.Task<TierKvOfOrderKeyPayload> CreateAsync(
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Products.Kv.TierKvOptions? options = null,
        global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Payload>? formatter = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Products.Kv.KvRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        options ??= s_defaultOptions;
        var ring = new RingImpl(global::TC.Tier.Products.Kv.TierKvAssembly.RingSettings(fs, options), fs);
        global::TC.Tier.Contracts.Structures.IIndex<global::Golden.Fixtures.OrderKey> index = options.IndexKind switch
        {
            global::TC.Tier.Products.Kv.KvIndexKind.Hash => new HashIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.HashSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.BTree => new BTreeIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.BTreeSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.SkipList => new SkipListIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.SkipListSettings(fs, options), ring),
            _ => throw new global::System.ArgumentOutOfRangeException(
                nameof(options), options.IndexKind, "未知主索引类型"),
        };
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<global::Golden.Fixtures.OrderKey>? rangeIndex =
            options.EnableRangeIndex
                ? global::TC.Tier.Products.Kv.TierKvAssembly.CreateRangeIndex(fs, options, ring)
                : null;
        var kv = new TierKvOfOrderKeyPayload(ring, index, options, formatter ?? s_formatter, logger, rangeIndex);
        kv.Initialize(hints);
        await kv.WaitForReadyAsync(ct).ConfigureAwait(false);
        return kv;
    }

    /// <summary>内嵌 Ring 派生实现——派生肢获得 protected internal 构造权（开放泛型零构造，同 RingOfT 形态）。</summary>
    private sealed class RingImpl : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<global::Golden.Fixtures.OrderKey>
    {
        public RingImpl(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
            global::TC.Tier.Core.IO.IFileSystem fs)
            : base(settings, fs)
        {
        }
    }

    /// <summary>内嵌探测族派生实现——resolver 挂 Ring 本体（tag 判等闭环回读数据面）。</summary>
    private sealed class HashIndexImpl : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<global::Golden.Fixtures.OrderKey>
    {
        public HashIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（BTree）——resolver 挂 Ring 本体。</summary>
    private sealed class BTreeIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<global::Golden.Fixtures.OrderKey>
    {
        public BTreeIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（SkipList）——resolver 挂 Ring 本体。</summary>
    private sealed class SkipListIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<global::Golden.Fixtures.OrderKey>
    {
        public SkipListIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<global::Golden.Fixtures.OrderKey> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }
}
/// <summary><c>[KvStore(typeof(Int64), typeof(Position))]</c> 封闭形态——开放泛型产品类的编译期封闭（[RingKey] 同款先例），消费面只见本类型；formatter 按 TValue 自动发射（D6/D7）。</summary>
public sealed class TierKvOfLongPosition : global::TC.Tier.Products.Kv.TierKv<long, global::Golden.Fixtures.Position>
{
    private static readonly global::TC.Tier.Products.Kv.TierKvOptions s_defaultOptions = global::TC.Tier.Products.Kv.TierKvOptions.Default.WithIndexKind((global::TC.Tier.Products.Kv.KvIndexKind)1);

    private static readonly global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Position> s_formatter = global::TC.Tier.Products.Kv.ValueFormatters.Blittable<global::Golden.Fixtures.Position>();

    public TierKvOfLongPosition(global::TC.Tier.Runtime.Structures.Ring.RingBase<long> ring,
        global::TC.Tier.Contracts.Structures.IIndex<long> index,
        global::TC.Tier.Products.Kv.TierKvOptions options,
        global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Position> formatter,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<long>? rangeIndex = null)
        : base(ring, index, options, formatter, logger, rangeIndex)
    {
    }

    /// <summary>★ 工厂（异步）：默认装配（Ring + 索引按 Options.IndexKind 路由，Settings 经 TierKvAssembly 翻译）+ Initialize + WaitForReadyAsync 一步到位；options/formatter 显式注入胜出。</summary>
    public static async global::System.Threading.Tasks.Task<TierKvOfLongPosition> CreateAsync(
        global::TC.Tier.Core.IO.IFileSystem fs,
        global::TC.Tier.Products.Kv.TierKvOptions? options = null,
        global::TC.Tier.Products.Kv.IValueFormatter<global::Golden.Fixtures.Position>? formatter = null,
        global::TC.Tier.Core.Logging.ILogger? logger = null,
        global::TC.Tier.Products.Kv.KvRecoveryHints hints = default,
        global::System.Threading.CancellationToken ct = default)
    {
        options ??= s_defaultOptions;
        var ring = new RingImpl(global::TC.Tier.Products.Kv.TierKvAssembly.RingSettings(fs, options), fs);
        global::TC.Tier.Contracts.Structures.IIndex<long> index = options.IndexKind switch
        {
            global::TC.Tier.Products.Kv.KvIndexKind.Hash => new HashIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.HashSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.BTree => new BTreeIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.BTreeSettings(fs, options), ring),
            global::TC.Tier.Products.Kv.KvIndexKind.SkipList => new SkipListIndexImpl(
                fs, global::TC.Tier.Products.Kv.TierKvAssembly.SkipListSettings(fs, options), ring),
            _ => throw new global::System.ArgumentOutOfRangeException(
                nameof(options), options.IndexKind, "未知主索引类型"),
        };
        global::TC.Tier.Runtime.Structures.SortedIndex.SortedIndexBase<long>? rangeIndex =
            options.EnableRangeIndex
                ? global::TC.Tier.Products.Kv.TierKvAssembly.CreateRangeIndex(fs, options, ring)
                : null;
        var kv = new TierKvOfLongPosition(ring, index, options, formatter ?? s_formatter, logger, rangeIndex);
        kv.Initialize(hints);
        await kv.WaitForReadyAsync(ct).ConfigureAwait(false);
        return kv;
    }

    /// <summary>内嵌 Ring 派生实现——派生肢获得 protected internal 构造权（开放泛型零构造，同 RingOfT 形态）。</summary>
    private sealed class RingImpl : global::TC.Tier.Runtime.Structures.Ring.BlittableRing<long>
    {
        public RingImpl(global::TC.Tier.Runtime.Structures.Ring.BlittableRingSettings settings,
            global::TC.Tier.Core.IO.IFileSystem fs)
            : base(settings, fs)
        {
        }
    }

    /// <summary>内嵌探测族派生实现——resolver 挂 Ring 本体（tag 判等闭环回读数据面）。</summary>
    private sealed class HashIndexImpl : global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndex<long>
    {
        public HashIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.ProbingIndex.HashIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<long> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（BTree）——resolver 挂 Ring 本体。</summary>
    private sealed class BTreeIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndex<long>
    {
        public BTreeIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.BTreeIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<long> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }

    /// <summary>内嵌比较族派生实现（SkipList）——resolver 挂 Ring 本体。</summary>
    private sealed class SkipListIndexImpl : global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndex<long>
    {
        public SkipListIndexImpl(global::TC.Tier.Core.IO.IFileSystem fs,
            global::TC.Tier.Runtime.Structures.SortedIndex.SkipListIndexSettings settings,
            global::TC.Tier.Contracts.Structures.IKeyResolver<long> resolver)
            : base(fs, settings, keyResolver: resolver)
        {
        }
    }
}
