// <auto-generated/>
#pragma warning disable 1591 // 生成 Codec 成员不进 API 文档（DocFX 从 XML 注释取语义）
namespace Golden.Fixtures;

public static class HeaderFixtureCodec
{
    public const int StructSize = 30;

    public const int Offset_Magic = 0;
    public const int Size_Magic = 4;
    public const int Offset_Version = 4;
    public const int Size_Version = 2;
    public const int Offset_Flags = 6;
    public const int Size_Flags = 2;
    public const int Offset_Seq = 8;
    public const int Size_Seq = 8;
    public const int Offset_Delta = 16;
    public const int Size_Delta = 8;
    public const int Offset_Count = 24;
    public const int Size_Count = 4;
    public const int Offset_Raw = 28;
    public const int Size_Raw = 1;
    public const int Offset_State = 29;
    public const int Size_State = 1;

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static uint Read_Magic(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(0, 4));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort Read_Version(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(4, 2));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort Read_Flags(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(6, 2));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ulong Read_Seq(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(source.Slice(8, 8));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static long Read_Delta(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(source.Slice(16, 8));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static int Read_Count(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(24, 4));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static byte Read_Raw(System.ReadOnlySpan<byte> source)
        => source[28];

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Golden.Fixtures.TinyState Read_State(System.ReadOnlySpan<byte> source)
        => (Golden.Fixtures.TinyState)source[29];

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Magic(System.Span<byte> dest, uint value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(0, 4), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Version(System.Span<byte> dest, ushort value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(4, 2), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Flags(System.Span<byte> dest, ushort value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(6, 2), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Seq(System.Span<byte> dest, ulong value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(dest.Slice(8, 8), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Delta(System.Span<byte> dest, long value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(dest.Slice(16, 8), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Count(System.Span<byte> dest, int value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(dest.Slice(24, 4), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Raw(System.Span<byte> dest, byte value)
    {
        dest[28] = value;
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_State(System.Span<byte> dest, Golden.Fixtures.TinyState value)
    {
        dest[29] = (byte)value;
    }

    /// <summary>合法默认实例——[ValidEquals] 字段自动填常量（写侧只填变化字段）。</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static HeaderFixture Create()
    {
        return new HeaderFixture
        {
            Magic = 1145590338u,
            Version = (ushort)512,
            Flags = default,
            Seq = default,
            Delta = default,
            Count = default,
            Raw = default,
            State = default
        };
    }

    public static bool Validate(in HeaderFixture value)
    {
        if (value.Magic != 1145590338u) return false;
        if (value.Version != (ushort)512) return false;
        if ((value.Flags & (ushort)19) != (ushort)19) return false;
        return true;
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write(System.Span<byte> dest, in HeaderFixture value, bool validate = false)
    {
        if (dest.Length < 30)
            throw new System.ArgumentException("Buffer too small");
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(0, 4), validate ? 1145590338u : value.Magic);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(4, 2), validate ? (ushort)512 : value.Version);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(6, 2), value.Flags);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(dest.Slice(8, 8), value.Seq);
        System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(dest.Slice(16, 8), value.Delta);
        System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(dest.Slice(24, 4), value.Count);
        dest[28] = value.Raw;
        dest[29] = (byte)value.State;
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static HeaderFixture Read(System.ReadOnlySpan<byte> source)
    {
        if (source.Length < 30)
            throw new System.ArgumentException("Buffer too small");
        return new HeaderFixture
        {
            Magic = System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(0, 4)),
            Version = System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(4, 2)),
            Flags = System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(6, 2)),
            Seq = System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(source.Slice(8, 8)),
            Delta = System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(source.Slice(16, 8)),
            Count = System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(24, 4)),
            Raw = source[28],
            State = (Golden.Fixtures.TinyState)source[29]
        };
    }

    /// <summary>原地 OR 设置 HeaderFixture.Flags（偏移 6）。Seal 用。</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void OrFlags(System.Span<byte> dest, ushort flagsToSet)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(6, 2), (ushort)(System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(dest.Slice(6, 2)) | flagsToSet));
    }

    /// <summary>判断 HeaderFixture.Magic == 0（偏移 0）——空位 record。</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static bool IsEmptyMagic(System.ReadOnlySpan<byte> source)
    {
        return System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(0, 4)) == 0;
    }

}
