// <auto-generated/>
#pragma warning disable 1591 // 生成 Codec 成员不进 API 文档（DocFX 从 XML 注释取语义）
namespace Golden.Fixtures;

internal static class NestedHeaderCodec
{
    public const int StructSize = 8;

    public const int Offset_Kind = 0;
    public const int Size_Kind = 4;
    public const int Offset_Seq = 4;
    public const int Size_Seq = 4;

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static uint Read_Kind(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(0, 4));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static uint Read_Seq(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(4, 4));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Kind(System.Span<byte> dest, uint value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(0, 4), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Seq(System.Span<byte> dest, uint value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(4, 4), value);
    }

    /// <summary>合法默认实例——[ValidEquals] 字段自动填常量（写侧只填变化字段）。</summary>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Holder.NestedHeader Create()
    {
        return new Holder.NestedHeader
        {
            Kind = 7u,
            Seq = default
        };
    }

    public static bool Validate(in Holder.NestedHeader value)
    {
        if (value.Kind != 7u) return false;
        return true;
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write(System.Span<byte> dest, in Holder.NestedHeader value, bool validate = false)
    {
        if (dest.Length < 8)
            throw new System.ArgumentException("Buffer too small");
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(0, 4), validate ? 7u : value.Kind);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(4, 4), value.Seq);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Holder.NestedHeader Read(System.ReadOnlySpan<byte> source)
    {
        if (source.Length < 8)
            throw new System.ArgumentException("Buffer too small");
        return new Holder.NestedHeader
        {
            Kind = System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(0, 4)),
            Seq = System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(4, 4))
        };
    }

}
