// <auto-generated/>
#pragma warning disable 1591 // 生成 Codec 成员不进 API 文档（DocFX 从 XML 注释取语义）
namespace Golden.Fixtures;

public static class ContainerFixtureCodec
{
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Golden.Fixtures.AddressFixture Read_Addr(System.ReadOnlySpan<byte> source)
        => Golden.Fixtures.AddressFixtureCodec.Read(source.Slice(0, 16));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Golden.Fixtures.WideState Read_Mode(System.ReadOnlySpan<byte> source)
        => (Golden.Fixtures.WideState)System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(16, 4));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ulong Read_Meta(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(source.Slice(20, 8));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Golden.Fixtures.AddressFixture Read_Tail(System.ReadOnlySpan<byte> source)
        => Golden.Fixtures.AddressFixtureCodec.Read(source.Slice(28, 16));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort Read_Len(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(44, 2));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Addr(System.Span<byte> dest, Golden.Fixtures.AddressFixture value)
    {
        Golden.Fixtures.AddressFixtureCodec.Write(dest.Slice(0, 16), in value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Mode(System.Span<byte> dest, Golden.Fixtures.WideState value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(16, 4), (uint)value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Meta(System.Span<byte> dest, ulong value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(dest.Slice(20, 8), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Tail(System.Span<byte> dest, Golden.Fixtures.AddressFixture value)
    {
        Golden.Fixtures.AddressFixtureCodec.Write(dest.Slice(28, 16), in value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Len(System.Span<byte> dest, ushort value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(44, 2), value);
    }

    public static bool Validate(in ContainerFixture value)
    {
        if (value.Meta == 0) return false;
        if (value.Len < 0 || value.Len > 255) return false;
        return true;
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write(System.Span<byte> dest, in ContainerFixture value, bool validate = false)
    {
        if (dest.Length < 46)
            throw new System.ArgumentException("Buffer too small");
        Golden.Fixtures.AddressFixtureCodec.Write(dest.Slice(0, 16), in value.Addr);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(dest.Slice(16, 4), (uint)value.Mode);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(dest.Slice(20, 8), value.Meta);
        Golden.Fixtures.AddressFixtureCodec.Write(dest.Slice(28, 16), in value.Tail);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest.Slice(44, 2), value.Len);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ContainerFixture Read(System.ReadOnlySpan<byte> source)
    {
        if (source.Length < 46)
            throw new System.ArgumentException("Buffer too small");
        return new ContainerFixture
        {
            Addr = Golden.Fixtures.AddressFixtureCodec.Read(source.Slice(0, 16)),
            Mode = (Golden.Fixtures.WideState)System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(source.Slice(16, 4)),
            Meta = System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(source.Slice(20, 8)),
            Tail = Golden.Fixtures.AddressFixtureCodec.Read(source.Slice(28, 16)),
            Len = System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(44, 2))
        };
    }

}
