// <auto-generated/>
#pragma warning disable 1591 // 生成 Codec 成员不进 API 文档（DocFX 从 XML 注释取语义）
namespace Golden.Fixtures;

public static class BigEndianFixtureCodec
{
    public const int StructSize = 8;

    public const int Offset_Id = 0;
    public const int Size_Id = 2;
    public const int Offset_Flags = 2;
    public const int Size_Flags = 2;
    public const int Offset_Value = 4;
    public const int Size_Value = 4;

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort Read_Id(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(source.Slice(0, 2));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static ushort Read_Flags(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(source.Slice(2, 2));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static uint Read_Value(System.ReadOnlySpan<byte> source)
        => System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(source.Slice(4, 4));

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Id(System.Span<byte> dest, ushort value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(dest.Slice(0, 2), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Flags(System.Span<byte> dest, ushort value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(dest.Slice(2, 2), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write_Value(System.Span<byte> dest, uint value)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(dest.Slice(4, 4), value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write(System.Span<byte> dest, in BigEndianFixture value, bool validate = false)
    {
        if (dest.Length < 8)
            throw new System.ArgumentException("Buffer too small");
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(dest.Slice(0, 2), value.Id);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(dest.Slice(2, 2), value.Flags);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(dest.Slice(4, 4), value.Value);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static BigEndianFixture Read(System.ReadOnlySpan<byte> source)
    {
        if (source.Length < 8)
            throw new System.ArgumentException("Buffer too small");
        return new BigEndianFixture
        {
            Id = System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(source.Slice(0, 2)),
            Flags = System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(source.Slice(2, 2)),
            Value = System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(source.Slice(4, 4))
        };
    }

}
