// <auto-generated/>
#pragma warning disable 1591 // 生成 Codec 成员不进 API 文档（DocFX 从 XML 注释取语义）
namespace Golden.Fixtures;

public static class PlainFixtureCodec
{
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write(System.Span<byte> dest, in PlainFixture value, bool validate = false)
    {
        if (dest.Length < 8)
            throw new System.ArgumentException("Buffer too small");
        System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(dest.Slice(0, 4), value.A);
        System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(dest.Slice(4, 4), value.B);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static PlainFixture Read(System.ReadOnlySpan<byte> source)
    {
        if (source.Length < 8)
            throw new System.ArgumentException("Buffer too small");
        return new PlainFixture
        {
            A = System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(0, 4)),
            B = System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(4, 4))
        };
    }

}
