// <auto-generated/>
#pragma warning disable 1591 // 生成 Codec 成员不进 API 文档（DocFX 从 XML 注释取语义）
namespace Golden.Fixtures;

public static class AddressFixtureCodec
{
    public const int StructSize = 16;

    public const int Offset_High = 0;
    public const int Size_High = 8;
    public const int Offset_Low = 8;
    public const int Size_Low = 8;

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static void Write(System.Span<byte> dest, in AddressFixture value, bool validate = false)
    {
        if (dest.Length < 16)
            throw new System.ArgumentException("Buffer too small");
        System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(dest.Slice(0, 8), value.High);
        System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(dest.Slice(8, 8), value.Low);
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static AddressFixture Read(System.ReadOnlySpan<byte> source)
    {
        if (source.Length < 16)
            throw new System.ArgumentException("Buffer too small");
        return new AddressFixture
        {
            High = System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(source.Slice(0, 8)),
            Low = System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(source.Slice(8, 8))
        };
    }

}
